update yaml windows, conftest, & pytest.ini

diff --git a/.github/workflows/automation-test-workflow.yaml b/.github/workflows/automation-test-workflow.yaml
--- a/.github/workflows/automation-test-workflow.yaml
+++ b/.github/workflows/automation-test-workflow.yaml
@@ -55,22 +55,36 @@
 #            [Environment]::SetEnvironmentVariable("PASSWORD_GENERAL", $secretValue2, "Machine")
 #            Add-Content -Path $env:GITHUB_ENV "PASSWORD_GENERAL=$secretValue2"
 
-        - name: Create Directory --> Test/reports
-          run: | 
+#        - name: Create Directory --> Test/reports
+#          run: |
+#            cd Tests
+#            mkdir -p reports
+        - name: Create Directory --> Tests/reports & screenshots
+          run: |
             cd Tests
             mkdir -p reports
+            mkdir -p screenshots # Pastikan direktori screenshots dibuat
 
         - name: Run Pytest
           run: | 
             cd Tests
             python -m pytest -vs --browser=chrome --url=testing --html=./reports/automation_test_report_on_chrome_win.html --self-contained-html
 
-        - name: Upload Report to Github Artifact
+#        - name: Upload Report to Github Artifact
+#          uses: actions/upload-artifact@v4
+#          if: success() || failure()
+#          with:
+#            name: Automation_Test_Report
+#            path: Tests/reports/automation_test_report_on_chrome_win.html
+        - name: Upload Report and Screenshots to Github Artifact
           uses: actions/upload-artifact@v4
           if: success() || failure()
           with:
-            name: Automation_Test_Report
-            path: Tests/reports/automation_test_report_on_chrome_win.html
+            name: Automation_Test_Report_Chrome_Win
+            path: |
+              Tests/reports/automation_test_report_on_chrome_win.html
+              Tests/screenshots # Upload folder screenshots
+
     # ------------------- JOB 2: Run Test on Safari (macOS) -------------------
     test-safari-macos:
       timeout-minutes: 120
